# Generated by Django 3.2.18 on 2023-03-18 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
